name: Testing stuff

on:
  push:
    branches:
      - master
      - commit-logs
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: check condition with false
        if:  ${{!contains(toJson(github.event.commits.*.message), '#skip')}}
        run: echo "false"
      - name: check condition with true
        if: ${{contains(toJson(github.event.commits.*.message), '#skip')}}
        run: echo "true"
      - name: Test Success
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ success() }}
          with:
              severity: info
              details: Test Succeeded!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ failure() }}
          with:
              severity: error
              details: Test Failed!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Cancelled
          uses: rjstone/discord-webhook-notify@v1
          if: ${{ cancelled() }}
          with:
              severity: warn
              details: Test Cancelled!
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        