name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: npm run eslint
        run: npm run eslint
      - name: npm run build
        run: npm run build
      - name: npm run test
        run: npm run test-jest
      - uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deployment
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fs-part11-workflow"
          heroku_email: "tautvydas.glav@gmail.com"
          healthcheck: "https://fs-part11-workflow.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: build Failed
          description: commit ${{toJson(github.event.commits.*.url)}} by ${{toJson(github.actor)}} broke the build
      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{success() && github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: a new version deployed
          description: to https://fs-part11-workflow.herokuapp.com/ by ${{toJson(github.actor)}}
  tag_release:
    if: ${{!contains(toJson(github.event.commits.*.message), '#skip')}}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        details: Test Failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        text: build Failed
        description: commit ${{toJson(github.event.commits.*.url)}} by ${{toJson(github.actor)}} broke the build
